# Generated by Django 2.2.12 on 2020-06-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('R1', models.IntegerField(default=0, verbose_name='3 balls + can')),
                ('R2', models.IntegerField(default=0)),
                ('R3', models.IntegerField(default=0)),
            ],
        ),
    ]
