# Generated by Django 2.2.12 on 2020-06-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jughead4', '0002_post_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
